cache-key: &cache-key
  key: app-{{ .Branch }}-{{ checksum "package-lock.json" }}
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          <<: *cache-key
      - run: npm install
      - save_cache:
          <<: *cache-key
          paths:
            - "node_modules"
      - run: npm run test:coverage-ci
      - store_artifacts:
          path: coverage
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          <<: *cache-key
      - run: npm install
      - save_cache:
          <<: *cache-key
          paths:
            - "node_modules"
      - run: npm run build
      - store_artifacts:
          path: dist/app1
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
