cache_key: &cache_key
  key: app-{{ .Branch }}-{{ checksum "package-lock.json" }}
save_cache: &save_cache
  <<: *cache_key
  paths:
    - "node_modules"
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run: npm install
      - save_cache:
          <<: *save_cache
      - run: npm run test:coverage-ci
      - store_artifacts:
          path: coverage
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run: npm install
      - save_cache:
          <<: *save_cache
      - run: npm run build
      - store_artifacts:
          path: dist/app1
          destination: /
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
